language: node

git:
  depth: 10

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^v[0-9]/

cache:
  directories:
  - ${HOME}/.ccache

notifications:
  email: false
  slack:
    secure: Gnrl9VgCtWnBpN1UgLmE5TLnYR91X/bQQ3OavskN9vMXrDO5l8Aqx78u7pcE42hBYjLh5NaKyhQkbyPa4o5A+HvG1rj/OJyVvDAZwzktKn+O3VbqvT5Pqq/1ohHxVNZz4M2Ho5ROGhd+u1UhrAkANPM4/Xvd0gFiPTuCngeoZnE=
    on_success: change
    on_failure: change

sudo: false

env:
  global:
   - JOBS=4
   - CCACHE_TEMPDIR=/tmp/.ccache-temp
   - CCACHE_COMPRESS=1
   - CASHER_TIME_OUT=1000
   - secure: KitzGZjoDblX/3heajcvssGz0JnJ/k02dr2tu03ksUV+6MogC3RSQudqyKY57+f8VyZrcllN/UOlJ0Q/3iG38Oz8DljC+7RZxtkVmE1SFBoOezKCdhcvWM12G3uqPs7hhrRxuUgIh0C//YXEkulUrqa2H1Aj2xeen4E3FAqEoy0=
   - secure: WLGmxl6VTVWhXGm6X83GYNYzPNsvTD+9usJOKM5YBLAdG7cnOBQBNiCCUKc9OZMMZVUr3ec2/iigakH5Y8Yc+U6AlWKzlORyqWLuk4nFuoedu62x6ocQkTkuOc7mHiYhKd21xTGMYauaZRS6kugv4xkpGES2UjI2T8cjZ+LN2jU=

addons_default: &apt_packages
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev', 'zlib1g-dev', 'make', 'apport', 'gdb' ]

script_default: &build_and_publish
    # still happening as of sept 27, 2016: https://github.com/travis-ci/travis-ci/issues/6307
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        rvm get head || true
      fi
    - nvm install ${NODE}
    - nvm use ${NODE}
    - source ./scripts/build.sh
    - ./scripts/publish.sh

matrix:
  include:
    # # Linux
    # - os: linux
    #   env: NODE="4" BUILD_TYPE=Release
    #   addons: *apt_packages
    #   script: *build_and_publish
    # - os: linux
    #   env: NODE="4" BUILD_TYPE=Debug NPM_FLAGS="--debug"
    #   addons: *apt_packages
    #   script: *build_and_publish
    # - os: linux
    #   env: NODE="6" BUILD_TYPE=Release
    #   addons: *apt_packages
    #   script: *build_and_publish
    # - os: linux
    #   env: NODE="6" BUILD_TYPE=Debug NPM_FLAGS="--debug"
    #   addons: *apt_packages
    #   script: *build_and_publish
    # # OS X
    # - os: osx
    #   # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
    #   osx_image: xcode7.3
    #   env: NODE="4" BUILD_TYPE=Release
    #   script: *build_and_publish
    # - os: osx
    #   osx_image: xcode7.3
    #   env: NODE="4" BUILD_TYPE=Debug NPM_FLAGS="--debug"
    #   script: *build_and_publish
    # - os: osx
    #   # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
    #   osx_image: xcode7.3
    #   env: NODE="6" BUILD_TYPE=Release
    #   script: *build_and_publish
    - os: osx
      osx_image: xcode7.3
      env: NODE="6" BUILD_TYPE=Debug NPM_FLAGS="--debug"
      script: *build_and_publish
    # Linux coverage build
    # - os: linux
    #   env: NODE="4" BUILD_TYPE=Debug ENABLE_COVERAGE=On NPM_FLAGS="--debug"
    #   addons: *apt_packages
    #   script:
    #     - nvm install ${NODE}
    #     - nvm use ${NODE}
    #     - source ./scripts/build.sh
    #     - curl -S -f https://codecov.io/bash -o codecov
    #     - chmod +x codecov
    #     - ./codecov -x "llvm-cov gcov" -Z
